site_name: EvidenceSeeker-Ergebnisse

nav:
  - Home: ./index.md
  - Grundidee: main_idea.md

hooks: 
  - hooks/initialisation.py

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - abbr
  - pymdownx.snippets

use_directory_urls: false

theme:
  name: material
  custom_dir: overrides
  favicon: img/favicon.ico
  language: de
  palette:
    primary: deep purple
    accent: indigo
  icon:
    logo: material/clipboard-text-search-outline
    annotation: material/information
    repo: fontawesome/brands/github

#plugins: []

repo_url: https://github.com/debatelab/evidence-seeker
repo_name: debatelab/evidence-seeker
doku_url: https://debatelab.github.io/evidence-seeker
doku_name: Dokumentation

extra_css:
  - extra_styles.css