site_name: EvidenceSeeker-Ergebnisse

nav:
  - Home: index.md
#  - About: about.md

hooks: 
  - hooks/initialisation.py

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - abbr
  - pymdownx.snippets

theme:
  name: material
  custom_dir: overrides
  favicon: img/favicon.ico
  palette:
    primary: deep purple
    accent: indigo
  icon:
    logo: material/clipboard-text-search-outline
    annotation: material/information
    repo: fontawesome/brands/github

#plugins: []

repo_url: https://github.com/debatelab/evidence-seeker
repo_name: debatelab/evidence-seeker
doku_url: https://bwsyncandshare.kit.edu/f/4824063061
doku_name: Dokumentation
doku_icon: ./img/detective.png

copyright: 
  Copyright © 2024-2025 <a href="https://compphil2mmae.github.io/" target="_blank" rel="noopener">CompPhil²MMAE</a> @ KIT
  </br>
  Teil von <a href="https://compphil2mmae.github.io/research/kideku/">
    <img src="./img/logoKIdeKu.jpg" class="img-fluid" alt="KIdeKu" width="20">
  </a>

extra_css:
  - extra_styles.css