name: Build GitHub Pages
on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - run: pip install -r ./requirements.txt
    - run: mkdocs gh-deploy --config-file ./mkdocs.yml --force
    # just to be sure (should be handled already by mkdocs)
    - name: Ensure .nojekyll exists
      run: |
        git checkout gh-pages
        touch .nojekyll
        git add .nojekyll
        git commit -m "Add .nojekyll" || exit 0
        git push origin gh-pages
